/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package odev1;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
    public static boolean search(ArrayList<Integer> array, int e,int k,int l) {
        System.out.println("inside search");
        if (array == null) return false;
  
        for (int elt : array) {
          if (elt == e|| elt ==k || elt==e ||elt ==l) return true;
        }
        return false;
      }
}
